"""empty message

Revision ID: 9cb1e9f610b0
Revises: 0b0760792793
Create Date: 2020-04-27 21:24:54.655834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb1e9f610b0'
down_revision = '0b0760792793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('todos', 'until')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('until', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
